config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :categories
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  belongs_to :category

  enum importance: { low: 0, middle: 1, high: 2 }
  def self.ransackable_attributes(auth_object = nil)
    ["title", "category_id", "deadline_on", "importance"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  has_many :categories
  devise :database_authenticatable, :registerable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :authenticate_user!

  def after_sign_in_path_for(_resources)
    tasks_path
  end

  def after_sign_out_path_for(_resources)
    new_user_session_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < AuthController

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      redirect_to tasks_path, notice: "追加しました"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:category)
  end
end

app/controllers/tasks_controller.rb
class TasksController < AuthController

  def index
    @q = current_user.tasks.ransack(params[:q])
    @tasks = @q.result
  end

  def show
  end

  def new
    @task = current_user.tasks.build
  end

  def edit
    @task = current_user.tasks.find(params[:id])
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path, notice: "追加しました"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @task = current_user.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path, notice: "更新しました"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice: "削除しました"
  end

  private

  def task_params
    params.require(:task).permit(:title, :content, :category_id, :deadline_on, :importance)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/new.html.erb
<%= form_with model: @category do |form| %>
  <div>
    <%= form.label :category, "カテゴリ"%>
    <%= form.text_area :category, rows: 1 %>
  </div>
  <%= form.submit "追加" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task do |form| %>
  <div>
    <%= form.label :title, "件名" %>
    <%= form.text_area :title, rows: 1 %>
  </div>

  <div>
    <%= form.label :content, "詳細" %>
    <%= form.text_area :content, rows: 3 %>
  </div>

  <div>
    <%= form.label :category_id, "カテゴリ" %>
    <%= form.collection_select :category_id, Category.all, :id, :name, prompt: "選択してください" %>
  </div>

  <div>
    <%= form.label :deadline_on, "期限" %>
    <%= form.date_select :deadline_on %>
  </div>

  <div>
    <%= form.label :importance, "重要度" %>
    <%= form.collection_select :importance, Task.importances_i18n, :first, :last %>
  </div>

  <%= form.submit "更新", class: 'btn btn-primary' %>
  <%= link_to "削除", @task, class: 'btn btn-primary', data: { "turbo-method": :delete }  %>
<% end %>

app/views/tasks/index.html.erb
<%= link_to '新規作成', new_task_path, class: 'btn btn-primary' %>
<%= link_to 'カテゴリ', new_category_path, class: 'btn btn-primary' %>
<%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-primary' %>

<h1>ToDo一覧</h1>

<table class="table">
 <thead class="table-primary">
  <tr>
   <th width="30%"><%= sort_link(@q, :title, "件名") %></th>
   <th width="30%"><%= sort_link(@q, :category_id, "カテゴリ") %></th>
   <th width="30%"><%= sort_link(@q, :deadline_on, "期限") %></th>
   <th width="10%"><%= sort_link(@q, :importance, "重要度") %></th>
  </tr>
 </thead>

 <tbody>
  <% @tasks.each do |task| %>
   <tr>
    <td><%= link_to task.title, edit_task_path(task) %></td>
    <td><%= task.category&.name %></td>
    <td><%= l task.deadline_on %></td>
    <td><%= task.importance_i18n %></td>
   </tr>
  <% end %>
 </tbody>
</table>

app/views/tasks/new.html.erb
<%= form_with model: @task do |form| %>

  <% if @task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% @task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, "件名" %>
    <%= form.text_area :title, rows: 1 %>
  </div>

  <div>
    <%= form.label :content, "詳細" %>
    <%= form.text_area :content, rows: 3 %>
  </div>

  <div>
    <%= form.label :category_id, "カテゴリ" %>
    <%= form.collection_select :category_id, Category.all, :id, :name, prompt: "選択してください" %>
  </div>

  <div>
    <%= form.label :deadline_on, "期限" %>
    <%= form.date_field :deadline_on %>
  </div>

  <div>
    <%= form.label :importance, "重要度" %>
    <%= form.collection_select :importance, Task.importances_i18n, :first, :last %>
  </div>

  <%= form.submit "追加" %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>